services:

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=facility
      - POSTGRES_PASSWORD=ft0133fc
    volumes:
      - facility_db:/var/lib/postgresql/data

  facility:
    build:
      context: facility-website
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/facility
      - SPRING_DATASOURCE_USERNAME=facility
      - SPRING_DATASOURCE_PASSWORD=ft0133fc
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  angular-ui:
    build: facility-gestao
    container_name: facility-gestao
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  facility_db:
